// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API para generar cita médica de asegurados",
    "version": "1"
  },
  "paths": {
    "/appointments": {
      "post": {
        "summary": "Crear cita médica",
        "description": "Endpoint para programar una nueva cita médica para un paciente asegurado",
        "tags": [
          "Appointments"
        ],
        "operationId": "createAppointment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AppointmentRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Cita creada con éxito",
            "schema": {
              "$ref": "#/definitions/AppointmentResponse"
            }
          },
          "400": {
            "description": "Datos de entrada no válidos"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    },
    "/appointments/{insuredId}": {
      "get": {
        "summary": "Obtener citas por ID del asegurado",
        "description": "Obtener todas las citas de un asegurado",
        "tags": [
          "Appointments"
        ],
        "operationId": "getAppointmentsByInsuredId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "insuredId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de citas",
            "schema": {
              "$ref": "#/definitions/AppointmentListResponse"
            }
          },
          "404": {
            "description": "No se han encontrado citas para esta asegurado"
          },
          "500": {
            "description": "Error interno del servidor"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "k4nit9jt3h.execute-api.sa-east-1.amazonaws.com",
  "schemes": [
    "https"
  ]
};